name: CICD Backend Pipeline on Develop
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  ENVIRONMENT: "dev"  
  GH_REPOSITORY_NAME: GlyphGenAI
  S3_VERSION: "s3://csekspreprodbuilds/builds/eks"
  BUILD_NUMBER: ${{ github.run_number }}
  APP_COMPONENT: backend
  TAG_DEPLOYMENT: dev-latest
  IMAGE_DIGEST: 0

jobs:
  check-pr-close:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
