#test cicd - new test
name: CICD Backend Pipeline on Develop
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  ENVIRONMENT: "dev"  
  GH_REPOSITORY_NAME: GlyphGenAI
  S3_VERSION: "s3://csekspreprodbuilds/builds/eks"
  BUILD_NUMBER: ${{ github.run_number }}
  APP_COMPONENT: backend
  TAG_DEPLOYMENT: dev-latest
  IMAGE_DIGEST: 0

jobs:
  check-pr-close:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: "Get PR number if this is a PR"
        if: github.ref_name != 'master'
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: preDeployment
        id: preDeploy
        run: |
          echo "this step was executed"
          sleep 120
      - name: Check PR Status Before Deployment
        if: github.ref_name != 'main'
        id: check_pr
        run: |
          PR_STATE=$(gh pr view ${{ github.event.pull_request.number }} --json state -q '.state')
          echo "PR state: $PR_STATE"

          if [[ "$PR_STATE" != "OPEN" ]]; then
            echo "pr_open=false" >> "$GITHUB_OUTPUT"
            echo "PR is not OPEN. Skipping deployment."
            exit 0
          else
            echo "pr_open=true" >> "$GITHUB_OUTPUT"
            echo "PR is OPEN. Proceeding with deployment."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deployment
        if: steps.check_pr.outputs.pr_open == 'true'
        id: deploy
        run: |
          echo "this step was executed"
